version: '3.8'

services:
  main:
    build: 
      context: .
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ..:/workspace:cached
    command: sleep infinity